baseurl = "https://isaackhor.com/"
languageCode = "en-gb"
title = "Essence of Insanity"
copyright = "2017 Isaac Khor."

buildDrafts = false

# Pagination
paginate = 6
paginatePath = "page"

[permalinks]
 	blog = "/blog/:year/:title/"

[Params]
	DateForm = "2 Jan 2006"
	github = "https://github.com/ClarenceClark"
	tagline = "Ramblings of a lunatic"