baseurl = "https://isaackhor.com/"
languageCode = "en-gb"
title = "Isaac Khor's Blog"

buildDrafts = false
enableRobotsTXT = true
pygmentsCodefences = true
defaultContentLanguage = "en-gb"
sectionPagesMenu = "main"

rssLimit = 60

# Pagination
paginate = 60
paginatePath = "page"

[permalinks]
  blog = "/blog/:year/:title/"

[Params]
  DateForm = "2 Jan 2006"
  github = "https://github.com/IsaacKhor"
  tagline = "Random ramblings from a preson of questionable sanity"
  licenseFile = "/about/license/"

